#!/bin/sh
# Generates dev/opencloud/proxy.yaml: the default routes of the pinned
# release of the platform with the routes of the extensions applied on top.
#
# The proxy lets a default route be taken over only through the full policies
# block, and the defaults live in Go source, so they are read from the tag of
# the release on GitHub. Run it after every bump of OC_DOCKER_TAG in
# dev/.env and check the result in.
#
#   dev/scripts/gen-proxy-routes.sh [tag]
set -eu

here=$(cd "$(dirname "$0")" && pwd)
env_file="$here/../.env"
out="$here/../opencloud/proxy.yaml"
mapping="$here/../opencloud/role-mapping.yaml"

tag=${1:-}
if [ -z "$tag" ] && [ -f "$env_file" ]; then
	tag=$(sed -n 's/^OC_DOCKER_TAG=//p' "$env_file")
fi
if [ ! -f "$mapping" ]; then
	echo "no role mapping at $mapping" >&2
	exit 2
fi
if [ -z "$tag" ]; then
	echo "usage: $0 <tag>  (or set OC_DOCKER_TAG in dev/.env)" >&2
	exit 2
fi

source_url="https://raw.githubusercontent.com/opencloud-eu/opencloud/v${tag}/services/proxy/pkg/config/defaults/defaultconfig.go"
src=$(curl -fsSL "$source_url")

# One route per block of the Go literal. The three preview routes of the
# platform go to video-thumbnails instead of its webdav service.
routes=$(printf '%s\n' "$src" | awk '
	function quoted(line) { match(line, /"[^"]*"/); return substr(line, RSTART + 1, RLENGTH - 2) }
	/^func DefaultPolicies/ { in_func = 1; next }
	!in_func { next }
	/^}/ { exit }
	/^\t\t\t\t{$/ { in_route = 1; type = "prefix"; method = ""; endpoint = ""; service = ""; unprotected = ""; skip = ""; next }
	!in_route { next }
	/^\t\t\t\t},$/ {
		backend = ""
		if (type == "query" && endpoint ~ /\?preview=1$/) { backend = "http://video-thumbnails:9200"; service = ""; previews++ }
		printf "      - endpoint: %s\n", endpoint
		if (type != "prefix") printf "        type: %s\n", type
		if (method != "") printf "        method: %s\n", method
		if (service != "") printf "        service: %s\n", service
		if (backend != "") printf "        backend: %s\n", backend
		if (unprotected != "") printf "        unprotected: true\n"
		if (skip != "") printf "        skip_x_access_token: true\n"
		total++; in_route = 0; next
	}
	$1 == "Type:" { type = tolower($2); sub(/^config\./, "", type); sub(/route,$/, "", type) }
	$1 == "Method:" { method = quoted($0) }
	$1 == "Endpoint:" { endpoint = quoted($0) }
	$1 == "Service:" { service = quoted($0) }
	$1 == "Unprotected:" { unprotected = $2 }
	$1 == "SkipXAccessToken:" { skip = $2 }
	END {
		if (total == 0) { print "no routes found: the layout of the source changed" > "/dev/stderr"; exit 1 }
		if (previews != 3) { print "expected 3 preview routes, found " previews ": the routes of the platform changed" > "/dev/stderr"; exit 1 }
	}
')

first=$(printf '%s\n' "$routes" | head -1)
if [ "$first" != "      - endpoint: /" ]; then
	echo "the root route is not first any more; the proxy falls back on it by position" >&2
	exit 1
fi

count=$(printf '%s\n' "$routes" | grep -c '^      - endpoint:')

cat >"$out" <<EOF
# Generated by dev/scripts/gen-proxy-routes.sh from OpenCloud v${tag}: do not
# edit, run the script after a bump of OC_DOCKER_TAG.
#
# The default policy of the proxy, all ${count} routes of the release, with the
# routes of the extensions applied. The router keeps the first match per
# type, query before regex before prefix, so a default route can be taken
# over only by replacing the whole block; additional_policies is ignored once
# policies is set.
#
# Changes against the release:
#   - the three ?preview=1 routes go to video-thumbnails, which serves the
#     previews of videos itself and passes the rest on to the webdav service;
#   - /api/video-thumbnails/web/ serves the web app of the extension, before
#     login, so the web can load it;
#   - /api/file-activity is the feed.
#
# The file also carries the mapping of the roles of the identity provider,
# which the proxy reads from a file only, never from the environment.
policies:
  - name: default
    routes:
${routes}
      - endpoint: /api/video-thumbnails/web/
        backend: http://video-thumbnails:9200
        unprotected: true
      - endpoint: /api/file-activity
        backend: http://file-activity:9201

EOF

# The mapping of the roles lives in its own file: it belongs to the
# installation, the routes belong to the release.
cat "$here/../opencloud/role-mapping.yaml" >>"$out"

echo "wrote $out: $count routes of v${tag} plus 2 of the extensions and the role mapping"
